language: minimal
dist: xenial

services:
  - docker

git:
  depth: 1

before_install:
  - curl -sL https://ibm.biz/idt-installer | bash

script:
  - ibmcloud login -a https://api.ng.bluemix.net --apikey $IBMCLOUD_API_KEY > /dev/null
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
  - travis/build_and_push.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./travis/deploy.sh
    on:
      repo: IBM-Blockchain-Identity/verify-creds-samples
      tags: true