apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingressresource
  annotations:
    ingress.bluemix.net/redirect-to-https: "True"
    ingress.bluemix.net/client-max-body-size: size=10m
    ingress.bluemix.net/large-client-header-buffers: number=4 size=5m
spec:
  tls:
    - hosts:
        - CLUSTER_INGRESS_URL_HERE
        - DMV_CLUSTER_INGRESS_URL_HERE
        - IBMHR_CLUSTER_INGRESS_URL_HERE
        - BBCU_CLUSTER_INGRESS_URL_HERE
      secretName: credimi-dev
  rules:
    - host: DMV_CLUSTER_INGRESS_URL_HERE
      http:
        paths:
          - path: /
            backend:
              serviceName: gov-dmv
              servicePort: 80
    - host: IBMHR_CLUSTER_INGRESS_URL_HERE
      http:
        paths:
          - path: /
            backend:
              serviceName: ibm-hr
              servicePort: 80
    - host: BBCU_CLUSTER_INGRESS_URL_HERE
      http:
        paths:
          - path: /
            backend:
              serviceName: bbcu
              servicePort: 80
